### ISSUE TITLE
Suggestion - option to include formatting in column names

### ISSUE THREAD

**Issue by S-Wil** [kometenstaub/csv-to-md#6]
Thanks for your work here.

I would prefer to have the formatting inside the CSV column names.  This would make it easy to have different CSV files with different formatting.  It would also avoid the need to use or set up the setting file.

For example
Name (H1) | Location (H2) | Age (BO) | etc
Result:
# Name
## Location
**Age**

**Comment by kometenstaub** [comment]
The script is supposed to be a batch conversion tool. It is implemented in a way to only set up the settings for one file and then perform the action on all the other files. (Mostly for import from other tools. The other settings like file name column etc. would still need to be chosen with your suggestion.)

To make what you want, another script would be better I think. Some of the code could be reused, however you'd need to search for all the formatting with regex for every file which would make it more error-prone because the user would need to have chosen correct settings.

That's not something I want to make with this tool.
